package Controlleur;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class interface2Controller {
	@FXML
	private Button gc1;
	@FXML
	private Button gcf2;

	// Event Listener on Button[#gc1].onAction
	@FXML
	public void GestionCategorie(ActionEvent event) {
		// TODO Autogenerated
		try {
			//Parent root=new BorderPane();
			Parent root=FXMLLoader.load(getClass().getResource("/application/interface7.fxml"));
			Scene scene=new Scene(root,636,360);
			Stage stage= (Stage) ((Node) event.getSource()).getScene().getWindow();
			stage.setScene(scene);
			stage.show();
			
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#gcf2].onAction
	@FXML
	public void gestionCoffee(ActionEvent event) {
		
			try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/application/interface6.fxml"));
			Parent root = loader.load();

			    Scene scene = new Scene(root, 636, 360);
			    Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
			    stage.setScene(scene);
			    stage.show();
			    
			} catch (IOException e) {
			    e.printStackTrace();
			}
		
	}
}
