package Controlleur;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;

import java.net.URL;
import java.util.Optional;
import java.util.ResourceBundle;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import metier.Categorie;
import metier.CategorieCrud;
import metier.Coffee;
import metier.CoffeeCrud;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.TableColumn;

public class interface6Controller implements Initializable {
	@FXML
	private TableView <Coffee>tableproduit;
	@FXML
	private TableColumn <Coffee,Integer>id;
	@FXML
	private TableColumn<Coffee,String> nom;
	@FXML
	private TableColumn <Coffee,Integer> prix;
	@FXML
	private TableColumn <Coffee,String> description;
	@FXML
	private TableColumn <Coffee,Integer> catégorie;
	@FXML
	private Button a1;
	@FXML
	private Button s1;
	@FXML
	private Button m1;
	@FXML
	private TextField idtxt;
   
	@FXML
	private TextField nomtxt;
	 
	@FXML
	 private TextField descriptxt;
	@FXML
	private TextField categtxt;
	@FXML
	private TextField prixtxt;
	 @FXML
	    private Button pg;


	// Event Listener on Button[#a1].onAction
	 @FXML
	    void afficherproduit(MouseEvent event) {
	     Coffee c =  tableproduit.getSelectionModel().getSelectedItem();
	     idtxt.setText(""+c.getId());
	     nomtxt.setText(""+c.getNom());
	     prixtxt.setText(""+c.getPrix());
	     categtxt.setText(""+c.getCatégorie());
	     descriptxt.setText(""+c.getDescription());
	    }
	@FXML
	public void ajouter(ActionEvent event) {
		 int id = Integer.parseInt(idtxt.getText());
		    String nom = nomtxt.getText();
		    String description = descriptxt.getText();
		    int catégorie= Integer.parseInt(categtxt.getText());
		    int prix = Integer.parseInt(prixtxt.getText());

		    Coffee coffee = new Coffee(id,nom,description,catégorie,prix);
		    CoffeeCrud coffeeCrud = new CoffeeCrud();
		    coffeeCrud.add(coffee);

		    CoffeeCrud coffeeCrud2 = new CoffeeCrud();
		    ObservableList<Coffee> coffeeList = coffeeCrud2.getAll();
		    tableproduit.setItems(coffeeList);
		
	}
	// Event Listener on Button[#s1].onAction
	@FXML
	public void supprimer(ActionEvent event) {
		int id=Integer.parseInt(idtxt.getText());
		String nom=nomtxt.getText();
		String description=descriptxt.getText();
		int catégorie=Integer.parseInt(categtxt.getText());
		int prix=Integer.parseInt(prixtxt.getText());
		
		Coffee c=new Coffee(id,nom,description,catégorie,prix);
		CoffeeCrud coffee=new CoffeeCrud();
		coffee.delete(c);
		idtxt.setText("");
		nomtxt.setText("");
		descriptxt.setText("");
		prixtxt.setText("");
		CoffeeCrud cc=new CoffeeCrud();
		ObservableList<Coffee> listeCoffee= cc.getAll();
		tableproduit.setItems(listeCoffee);
		
	    }
	// Event Listener on Button[#m1].onAction
	@FXML
	public void modifier(ActionEvent event) {
		// TODO Autogenerated
		int id=Integer.parseInt(idtxt.getText());
		String nom=nomtxt.getText();
		String description=descriptxt.getText();
		int catégorie=Integer.parseInt(categtxt.getText());
		int prix=Integer.parseInt(prixtxt.getText());
		
		Coffee c=new Coffee(id,nom,description,catégorie,prix);
		CoffeeCrud coffee=new CoffeeCrud();
		coffee.update(c);
		CoffeeCrud cc=new CoffeeCrud();
		ObservableList<Coffee> listeCoffee= cc.getAll();
		tableproduit.setItems(listeCoffee);
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		id.setCellValueFactory(new PropertyValueFactory<>("id") );
		nom.setCellValueFactory(new PropertyValueFactory<>("nom") );
		prix.setCellValueFactory(new PropertyValueFactory<>("prix") );
		description.setCellValueFactory(new PropertyValueFactory<>("description") );
		catégorie.setCellValueFactory(new PropertyValueFactory<>("catégorie") );
		CoffeeCrud c=new CoffeeCrud();
		ObservableList<Coffee> listeCoffee= c.getAll();
		tableproduit.setItems(listeCoffee);
		
		
	}
	@FXML
    void retour(ActionEvent event) {
		try {
			//Parent root=new BorderPane();
			Parent root=FXMLLoader.load(getClass().getResource("/application/interface2.fxml"));
			Scene scene=new Scene(root,571,476);
			Stage stage= (Stage) ((Node) event.getSource()).getScene().getWindow();
			stage.setScene(scene);
			stage.show();
			
		} catch(Exception e) {
			e.printStackTrace();
		}
    }
}
