package Controlleur;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Alert.AlertType;

import java.util.Optional;

import javafx.event.ActionEvent;

public class interface3Controller {
	@FXML
	private Button a1;
	@FXML
	private Button a2;
	@FXML
	private Button m1;
	@FXML
	private Button s1;
	@FXML
	private Button m2;
	@FXML
	private Button s2;

	// Event Listener on Button[#a1].onAction
	@FXML
	public void ajouter(ActionEvent event) {
		// TODO Autogenerated
		Alert alert=new Alert (AlertType.CONFIRMATION);
		alert.setTitle("merci!");
		alert.setContentText("etes vous sur de cette action ");
		Optional <ButtonType> rep=alert.showAndWait();
		if (rep.get()==ButtonType.OK)
			System.out.println("OK!");
	}
	// Event Listener on Button[#a2].onAction
	@FXML
	public void ajouter2(ActionEvent event) {
		// TODO Autogenerated
		Alert alert=new Alert (AlertType.CONFIRMATION);
		alert.setTitle("merci!");
		alert.setContentText("etes vous sur de cette action ");
		Optional <ButtonType> rep=alert.showAndWait();
		if (rep.get()==ButtonType.OK)
			System.out.println("OK!");
	}
	// Event Listener on Button[#m1].onAction
	@FXML
	public void modifier(ActionEvent event) {
		// TODO Autogenerated
		Alert alert=new Alert (AlertType.CONFIRMATION);
		alert.setTitle("merci!");
		alert.setContentText("etes vous sur de cette action ");
		Optional <ButtonType> rep=alert.showAndWait();
		if (rep.get()==ButtonType.OK)
			System.out.println("OK!");
	}
	// Event Listener on Button[#s1].onAction
	@FXML
	public void supprimer(ActionEvent event) {
		// TODO Autogenerated
		Alert alert=new Alert (AlertType.CONFIRMATION);
		alert.setTitle("merci!");
		alert.setContentText("etes vous sur de cette action ");
		Optional <ButtonType> rep=alert.showAndWait();
		if (rep.get()==ButtonType.OK)
			System.out.println("OK!");
	}
	// Event Listener on Button[#m2].onAction
	@FXML
	public void modifier2(ActionEvent event) {
		// TODO Autogenerated
		Alert alert=new Alert (AlertType.CONFIRMATION);
		alert.setTitle("merci!");
		alert.setContentText("etes vous sur de cette action ");
		Optional <ButtonType> rep=alert.showAndWait();
		if (rep.get()==ButtonType.OK)
			System.out.println("OK!");
	}
	// Event Listener on Button[#s2].onAction
	@FXML
	public void supprimer2(ActionEvent event) {
		// TODO Autogenerated
		Alert alert=new Alert (AlertType.CONFIRMATION);
		alert.setTitle("merci!");
		alert.setContentText("etes vous sur de cette action ");
		Optional <ButtonType> rep=alert.showAndWait();
		if (rep.get()==ButtonType.OK)
			System.out.println("OK!");
	}
}
